server:
  port: 2003
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sapo_daytwo?createDatabaseIfNotExist=true&useSSL=true"
    username: "root"
    password: "050120"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # cho phép Spring Boot ch?p nh?n các tham chi?u l?p l?i (circular references) trong các bean
  main:
    allow-circular-references: true