server:
  port: 2000
spring:
  #  datasource:
  #    url: "jdbc:mysql://localhost:3306/sql_injection?createDatabaseIfNotExist=true&useSSL=true"
  #    username: "root"
  #    password: "050120"
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update